#!/bin/sh
#
# Copyright (C) 2007 Fonality Inc. (fonality.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
clear
function setup_linksys {

IPADDR=$1
cat > /tftpboot/spa841.cfg <<EOF
<flat-profile>
  <Resync_Periodic ua="na">2</Resync_Periodic>
  <Profile_Rule ua="na">/spa\$MA.cfg</Profile_Rule>
 <!-- Proxy and Registration -->
  <Proxy_1_ ua="na">$IPADDR</Proxy_1_>
  <Primary_NTP_Server ua="na">$IPADDR</Primary_NTP_Server>
  <Voice_Mail_Number  ua="na">*97</Voice_Mail_Number>
  <Display_Name_1_ ua="na">\$USER</Display_Name_1_>
  <Dial_Plan_1_ ua="na">(**xxx|**xxxx|*xx|xxx*|xxx**|xxxx*|xxxx**[3469]11|0|00|[2-9]xxxxxx|1xxx[2-9]xxxxxxS0|xxxxxxxxxxxx.)</Dial_Plan_1_>
  <Time_Zone  ua="na">GMT-07:00</Time_Zone>
  <Text_Logo group="Phone/General">trixbox CE</Text_Logo> 
  <BMP_Picture_Download_URL group="Phone/General" /> 
  <Select_Logo group="Phone/General">Text Logo</Select_Logo> 
  <Select_Background_Picture group="Phone/General">Text Logo</Select_Background_Picture> 
  <!-- options: GMT-12:00/GMT-11:00/GMT-10:00/GMT-09:00/GMT-07:00/GMT-07:00/GMT-06:00/GMT-05:00/GMT-04:00/GMT-03:30/GMT-03:00/GMT-02:00/GMT-01:00/GMT/GMT+01:00/GMT+02:00/GMT+03:00/GMT+03:30/GMT+04:00/GMT+05:00/GMT+05:30/GMT+05:45/GMT+06:00/GMT+06:30/GMT+07:00/GMT+07:00/GMT+09:00/GMT+09:30/GMT+10:00/GMT+11:00/GMT+12:00/GMT+13:00 -->
  <Daylight_Saving_Time_Rule ua="na">start=3/8/7/02:0:0;end=11/1/7/02:0:0;save=1</Daylight_Saving_Time_Rule>
  <Call_Return_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Blind_Transfer_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Call_Back_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Call_Back_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_All_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_All_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_Busy_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_Busy_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_No_Ans_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Cfwd_No_Ans_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <CW_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <CW_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <CW_Per_Call_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <CW_Per_Call_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_CID_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_CID_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_CID_Per_Call_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_CID_Per_Call_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_ANC_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Block_ANC_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <DND_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <DND_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Secure_All_Call_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Secure_No_Call_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Secure_One_Call_Act_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Secure_One_Call_Deact_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Paging_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Call_Park_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Call_Pickup_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Call_UnPark_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Group_Call_Pickup_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Media_Loopback_Code group="Regional/Vertical_Service_Activation_Codes" /> 
  <Referral_Services_Codes group="Regional/Vertical_Service_Activation_Codes" /> 

</flat-profile>
EOF

cp /tftpboot/spa841.cfg /tftpboot/spa921.cfg 
cp /tftpboot/spa841.cfg /tftpboot/spa922.cfg 
cp /tftpboot/spa841.cfg /tftpboot/spa941.cfg 
cp /tftpboot/spa841.cfg /tftpboot/spa942.cfg 
cp /tftpboot/spa841.cfg /tftpboot/spa962.cfg

echo "Created /tftpboot/spaXXX.cfg, sip.cfg using $IPADDR for the proxy."
}

setup_linksys $1


