#!/bin/sh
# Version: 1.0
# Date: 12/20/07
#
# Copyright (C) 2007 Fonality Inc. (fonality.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# 1.0 - Kerry Garrison
#
echo ""
echo "--------------------------------------------------------------"
echo "Detecting PSTN cards"
echo "--------------------------------------------------------------"
echo ""
echo ""
/usr/sbin/ztcfg
amportal stop
/usr/sbin/genzaptelconf -d
service zaptel stop
service zaptel start

##
#We need to test to see if the zapata-auto.conf file is available
#If not we create a symlnk from zapata-channels.conf 
##
echo ""
echo ""
echo "Checking for zapata-auto.conf"
if [ -h /etc/asterisk/zapata-auto.conf ]
then
echo "No need to create symlink"
else
echo "Creating symlink for zapata-auto.conf"
ln -s /etc/asterisk/zapata-channels.conf /etc/asterisk/zapata-auto.conf
fi
echo ""
echo ""
amportal start
/usr/sbin/fxotune -s
asterisk -rx "zap show channels"


