GRANT USAGE ON *.* TO 'sugarcrm'@'localhost' IDENTIFIED BY PASSWORD '122c2d6239661971';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON `sugarcrm`.* TO 'sugarcrm'@'localhost';
